---
services:
  featherweb:
    image: "featherweb-api:dev"
    container_name: "featherweb"
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    # volumes:
    #   - ./featherweb/:/app/featherweb:delegated
    environment:
      - SHELL=/bin/bash
      - DB_HOST=database
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://developer:developer@database:5432/featherweb
      - DJANGO_READ_DOT_ENV_FILE=True
    depends_on:
      - database
      - redis

  database:
    image: "postgres:14.1-alpine"
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=developer
      - POSTGRES_USER=developer
      - POSTGRES_DB=featherweb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    restart: on-failure
    volumes:
      - redis:/data

volumes:
  postgres: {}
  redis: {}
